# Site settings
title: mileistone blog
email: xyc_sjtu@163.com
description: "Vision and Insight"
baseurl: ""
url: "http://mileistone.github.io"
github_username:  mileistone

cdn:
    jsdelivr:
        enabled: true

navs:
    -
        href: /
        label: Home
    -
        href: /categories/
        label: Categories
    -
        href: /about/
        label: About

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

